version: '3'
services:
  api:
    image: node:14-alpine
    command: npm run dev
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - '5000:5000'
  webapp:
    image: node:14-alpine
    command: npm run dev
    working_dir: /app
    depends_on:
      - api
    volumes:
      - ./webapp:/app
    ports:
      - '3000:3000'
  storybook:
    image: node:14-alpine
    command: npm run storybook
    working_dir: /app
    volumes:
      - ./webapp:/app
    ports:
      - '6006:6006'
